---
# See: https://launchpad.net/~ondrej/+archive/ubuntu/apache2
- name: Add PPA for Apache2 repository
  apt_repository:
    repo: ppa:ondrej/apache2

- name: Install Apache2
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Install Apache2 modules
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - libapache2-mod-fastcgi

- name: Enable Apache2 modules
  apache2_module:
    name: "{{ item }}"
    state: present 
  with_items:
    - fastcgi
    - proxy
    - proxy_fcgi
    - rewrite
    - expires
    - headers
  notify:
    - restart apache

- name: Write virtual hosts and configuration files onto the host
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: site.conf.j2
      dest: /etc/apache2/sites-available/site.conf
    - src: fqdn.conf.j2
      dest: /etc/apache2/conf-available/fqdn.conf

- name: Disable defaults virtual hosts
  file:
    path: "/etc/apache2/sites-enabled/{{ item }}"
    state: absent
  with_items:
    - 000-default.conf 
    - default-ssl.conf 
  notify:
    - restart apache

- name: Enable virtual hosts
  file:
    src: "/etc/apache2/sites-available/{{ item }}"
    dest: "/etc/apache2/sites-enabled/{{ item }}"
    state: link
  with_items:
    - site.conf
  notify:
    - restart apache

- name: Enable configuration files
  file:
    src: "/etc/apache2/conf-available/{{ item }}"
    dest: "/etc/apache2/conf-enabled/{{ item }}"
    state: link
  with_items:
    - fqdn.conf
  notify:
    - restart apache